research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A complete detailed research report with all relevant links used in researching {topic} and
    Include A list with 10 bullet points of the most relevant information about {topic}
    Formatted as markdown without '```'
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
    Use Second-Order Thinking, Logic, Reasoning and Ethics when creating the report.
  expected_output: >
    A fully fledge reports with the Title, Subtitles, mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
